# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PC maps' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PC maps
	pod 'Alamofire', '~> 4.4'
	pod 'Realm', '~> 2.6'
	pod 'ObjectMapper', '~> 2.2'
	pod 'RealmSwift', '~> 2.6'
	pod 'AlamofireObjectMapper', '~> 4.0'
	pod 'SVProgressHUD'
  target 'PC mapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PC mapsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
